version: '3.6'
services:
  iris:
    build: 
      context: ./objectscript
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 1972:1972
      - 52773:52773
      - 53773
    volumes:
      - ./:/irisdev/app
  java-quarkus:
    build:
      context: ./java/quarkus
      dockerfile: dockerfile
    ports:
      - "8081:8080"