# pull the official base image
FROM python:3.8.3

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DJANGO_DATABASE "prod"

# install dependencies
RUN pip install --upgrade pip 
COPY ./requirements.txt /usr/src/app
COPY ./intersystems_irispython-3.2.0-py3-none-any.whl /usr/src/app
RUN pip install intersystems_irispython-3.2.0-py3-none-any.whl
RUN pip install -r requirements.txt

# copy project
COPY . /usr/src/app

EXPOSE 8000

ENTRYPOINT [ "sh", "/usr/src/app/entrypoint.sh" ]
